name: Fetch APOD data from API

on:
  schedule:
    # Runs every day at 05:45 UTC
    - cron: "45 5 * * *"
  workflow_dispatch:  # allow manual run

jobs:
  fetch-and-commit:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get Tg session
        run: |
          echo "${{ secrets.TG_SESSION_BASE_64 }}" | base64 --decode > session.session

      - name: Set up secrets
        run: |
          echo "API_ID=${{ secrets.TG_API_ID }}" >> $GITHUB_ENV
          echo "API_HASH=${{ secrets.TG_API_HASH }}" >> $GITHUB_ENV

      - name: Get current date
        run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # You can change to '3.10', '3.12', etc.

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Run Python script
        run: |
          python3 main.py
        
      - name: Commit and push if changed
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data.json
          git add image.jpg
          git diff --cached --quiet || git commit -m "Update data.json from NASA APOD Tg Channel, $TODAY"
          git push
